# Generated by Django 3.2.4 on 2021-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата')),
                ('join_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда присоеденился')),
                ('city', models.CharField(max_length=50, verbose_name='Отслеживаемый город')),
                ('notification_time', models.TimeField(verbose_name='Время оповещений')),
                ('active_user', models.BooleanField(verbose_name='Оповещения активированы')),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
    ]
